### ISSUE TITLE
Use an auto formatter, such as autopep8, half, or black for consistent code style

### ISSUE THREAD

**Issue by mralext20** [rNintendoSwitch/MechaBowser#51]
Automatically formatting code would lead to less merge conflicts, a consistent style, and better readability. 

I have found a medium article about formatters. https://medium.com/3yourmind/auto-formatters-for-python-8925065f9505

My personal suggestion is black, because it requires no configuration. (Ford's truck came in any color - as long as it's black.) 

A good fallback is autopep8, as it's the 'default' in vscode. 

Vscode does allow black or yapf I'd you don't want to use autopep8.

**Comment by mralext20** [comment]
an example of some different formatters when ran on the current code:
orignal code: ![](https://this-is-a.stale-me.me/i/u1rr.png)

formatted with black: ![](https://this-is-a.stale-me.me/i/6xnk.png) (line length set to 120)

formatted with autopep8: ![](https://this-is-a.stale-me.me/i/lhqz.png) (line length set to 120)

formatted with yapf: ![](https://this-is-a.stale-me.me/i/mr3t.png) (line length set to 120)

my personal preference is with black.

**Comment by mralext20** [comment]
for completeness's sake:

i have formatted the current code with black, yapf and autopep8 and put each version on a different branch in my fork: [autopep8](https://github.com/mralext20/MechaBowser/tree/autopep8) [black](https://github.com/mralext20/MechaBowser/tree/black) [yapf](https://github.com/mralext20/MechaBowser/tree/yapf)

**Comment by 7bitlyrus** [comment]
Links to compares for Alex's branches:
[autopep8](https://github.com/rNintendoSwitch/MechaBowser/compare/master...mralext20:autopep8)
[black](https://github.com/rNintendoSwitch/MechaBowser/compare/master...mralext20:black)
[yapf](https://github.com/rNintendoSwitch/MechaBowser/compare/master...mralext20:yapf)
